### ISSUE TITLE
decide on endpoints

### ISSUE THREAD

**Issue by johnshiver** [andybeers/KingKai#8]
need to decide the endpoint names

for handshake, i propose:  king_kai_server/handshake

for time series, looks like you have a restful cadence in mind. works for me, just write out what you want so i can follow it

**Comment by andybeers** [comment]
Right now i'm calling the time series documents 'snapshots' -- that was a first take, happy to change it if there's something else that makes sense.

Handshake hardware info is under 'servers' resource.

Each of these resources is after the /api/ prefix.

localhost/api/servers (POST for handshake, GET to see list of all)
localhost/api/snapshots (POST for adding timeseries data, GET to see list of all)

Obviously we dont' want to get all snapshots, but that's next on the list

**Comment by johnshiver** [comment]
yeah routes all make sense to me, i think we can close issue
